### ISSUE TITLE
Pug template

### ISSUE THREAD

**Issue by beltranrengifo** [oliverfindl/vue-svg-inline-loader#10]
I think the basic usage it's not working with Pug templates. Am I right?

`img.suites__logo(
        src="@/assets/images/header/onesait-brand-logo.svg"
        svg-inline)`
![image](https://user-images.githubusercontent.com/19485114/50279102-1bf9f300-0449-11e9-83b8-08589c77e137.png)

`<img svg-inline src="@/assets/images/header/onesait-brand-logo.svg" alt="">`
![image](https://user-images.githubusercontent.com/19485114/50279141-36cc6780-0449-11e9-902e-0fc688d26d4b.png)

Thank you!

**Comment by beltranrengifo** [comment]
Ok! Maybe it can be pointed. It's mentioned about sprites, so I supposed it'll do it for standard images.
Thanks you

**Comment by oliverfindl** [comment]
Sure, I will update [README.md](https://github.com/oliverfindl/vue-svg-inline-loader/blob/master/README.md) at evening.

**Comment by oliverfindl** [comment]
I updated [README.md](https://github.com/oliverfindl/vue-svg-inline-loader/blob/master/README.md).

Closing this issue.
