### ISSUE TITLE
defs id's get replaced & scrambled

### ISSUE THREAD

**Issue by mesqueeb** [oliverfindl/vue-svg-inline-loader#11]
I have a problem that when I use this plugin all the `defs` variable `id`s all get minified to things like `a`, `b`, `c`, ... and this is the same for every svg on the page. This is causing problems that wrong variables are used since they all overlap now.

Is there any way to prevent this from happening?

**Comment by oliverfindl** [comment]
Hello,

look into `svgo` [option](https://github.com/oliverfindl/vue-svg-inline-loader/blob/master/(#configuration)) of loader. Configure it according to [SVGO](https://github.com/svg/svgo) configuration or set this option to `null` or `false` to disable it.

Thanks

**Comment by mesqueeb** [comment]
Thanks so much! Passing `{svgo: false}` fixed the problem for me!
