### ISSUE TITLE
Render warning with nuxt

### ISSUE THREAD

**Issue by schnetzi** [oliverfindl/vue-svg-inline-loader#13]
Hello there, I have a problem when rendering svgs in my nuxt project. It always shows me the following warning in the browser console:
`The client-side rendered virtual DOM tree is not matching server-rendered content. This is likely caused by incorrect HTML markup, for example nesting block-level elements inside <p>, or missing <tbody>. Bailing hydration and performing full client-side render.`

I am using the default config from the Readme file.
```
build: {
  /*
  ** You can extend webpack config here
  */
  extend(config, ctx) {
    // Run ESLint on save
    if (ctx.isDev && ctx.isClient) {
      config.module.rules.push({
        enforce: 'pre',
        test: /\.(js|vue)$/,
        loader: 'eslint-loader',
        exclude: /(node_modules)/,
      });

      const vueRule = config.module.rules.find(rule => {
        return rule.test.test('.vue');
      });
      vueRule.use = [
        {
          loader: vueRule.loader,
          options: vueRule.options,
        },
        {
          loader: 'vue-svg-inline-loader',
        },
      ];
      delete vueRule.loader;
      delete vueRule.options;
    }
  },
},
```

Is there anything wrong with the configuration or am I just missing anything or is it supposed to be like that?
Thanks in advance!

**Comment by oliverfindl** [comment]
Hello,

I'm not personally using [nuxt.js](https://nuxtjs.org/), so I have very limited knowledge about it. I tried to fiddling with my [nuxt.js example](https://github.com/oliverfindl/vue-svg-inline-loader/tree/master/examples/nuxt) (with [mode](https://nuxtjs.org/api/configuration-mode) set to spa and universal), but unfortunately I cannot reproduce your issue.

Can you provide a dummy repo, where would be this issue reproducible?

Thanks

**Comment by schnetzi** [comment]
Thanks for your fast reply. I am currently working on that: https://github.com/schnetzi/portfolio

**Comment by oliverfindl** [comment]
Hello,

I just tried:
```bash
$ git clone https://github.com/schnetzi/portfolio.git test

$ cd test

$ npm install

$ npm run dev # no warnings or errors

$ npm run build # no warnings or errors

$ npm run start # no warnings or errors

$ npm run generate # no warnings or errors
```

My environment is:
```bash
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.5 LTS
Release:        16.04
Codename:       xenial

$ npm -v
6.7.0

$ node -v
v10.15.1
```

Can you specify commands to encounter your issue?

Thanks

**Comment by schnetzi** [comment]
Hi,

sorry I think I was a little bit unclear. I only get the warning in the console of my Browser (Chrome).
What I am doing:

```
npm run dev
```

My environment:
```
OS
macOS Mojave Version 10.14.2

Chrome
Version 71.0.3578.98

$ npm -v
6.5.0

$ node -v
v11.6.0
```

**Comment by oliverfindl** [comment]
Hello,

I finally figured what is going on. You have modified vue rule in condition `if (ctx.isDev && ctx.isClient) { 
/* ... */ }`, but it has to be outside. This resulted in nuxt not using loader in ssr. If you move the code outside that condition it will work.

Please give feedback if it solved your issue.

Thanks

**Comment by schnetzi** [comment]
I will try it in a few hours when I am back and will give feedback.
Thanks a lot for your help 😊

**Comment by schnetzi** [comment]
@oliverfindl works like a charm. Thanks a lot! 🎉

**Comment by oliverfindl** [comment]
Glad to hear!
