### ISSUE TITLE
parseError when using math operator (> or >=) on root element

### ISSUE THREAD

**Issue by mrleblanc101** [oliverfindl/vue-svg-inline-loader#14]
Hi,
There is an issue with parsing of math operator. 
The plugin think that my ">" (greater than) symbol is the end of the opening tag of the root element and append the sprite to this location which break the whole page.
Greater than symbol inside string (v-if, v-show or ternary js operator) should be ignored.

Source code:
```html
<template>
    <div v-if="lastItem > 10">
        <!-- more -->
    </div>
</template>
```
Compiled code:
```
<template>
    <div v-if="lastItem ><svg xmlns="http://www.w3.org/2000/svg" style="display: none !important;"><symbol id="sprite-6e59d10b0d068a69ed07029d53a15aef" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 6 10"><path data-name="Polygone 2 copie 4 copy 2 copie" d="M0 5l6-5v10z" fill-rule="evenodd"/></symbol><symbol id="sprite-83def3b2274096294fe2023b84cc1ed6" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 6 10"><path data-name="Polygone 2 copie 4 copy 2 copie" d="M6 5l-6 5V0z" fill-rule="evenodd"/></symbol></svg> 10">
         <!-- more -->
    </div>
</template>
```
Expected result:
```html
<template>
    <div v-if="lastItem > 10">
        <svg xmlns="http://www.w3.org/2000/svg" style="display: none !important;"><symbol id="sprite-6e59d10b0d068a69ed07029d53a15aef" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 6 10"><path data-name="Polygone 2 copie 4 copy 2 copie" d="M0 5l6-5v10z" fill-rule="evenodd"/></symbol><symbol id="sprite-83def3b2274096294fe2023b84cc1ed6" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 6 10"><path data-name="Polygone 2 copie 4 copy 2 copie" d="M6 5l-6 5V0z" fill-rule="evenodd"/></symbol></svg>
        <!-- more -->
    </div>
</template>
```

**Comment by mrleblanc101** [comment]
Possible solution for now.
Wrap the whole component in a useless div so the sprite will be appended before the condition.
Exemple:
```
<template>
    <div>
        <div v-if="lastItem > 10">
            <!-- more -->
        </div>
    </div>
</template>
```
Result: 
```
<template>
    <div>
        
<svg xmlns="http://www.w3.org/2000/svg" style="display: none !important;"><symbol id="sprite-6e59d10b0d068a69ed07029d53a15aef" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 6 10"><path data-name="Polygone 2 copie 4 copy 2 copie" d="M0 5l6-5v10z" fill-rule="evenodd"/></symbol><symbol id="sprite-83def3b2274096294fe2023b84cc1ed6" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 6 10"><path data-name="Polygone 2 copie 4 copy 2 copie" d="M6 5l-6 5V0z" fill-rule="evenodd"/></symbol></svg>
        <div v-if="lastItem > 10">
            <!-- more -->
        </div>
    </div>
</template>
```

**Comment by oliverfindl** [comment]
Hello,

As you pointed out, problem lies in detection of opening tag of root element. Ignoring operators would be nice solution. Unfortunately it will be hard to implement, because currently its parsed with regular expressions. Easier solution would be to move svg sprite map before closing tag of root element.

I will try fix it this weekend. Until then, you can use your workaround.

So far thanks for reporting. I will respond to this thread when fixed version is online at npm.

**Comment by oliverfindl** [comment]
Hello,

I updated loader and published it to [npm](https://www.npmjs.com/package/vue-svg-inline-loader). Current version is [1.2.12](https://github.com/oliverfindl/vue-svg-inline-loader/releases/tag/v1.2.12).

I moved svg sprite map before closing tag of root element. This should solve issues with using operators in root element condition.

Please give me feedback if it works as expected.

Thanks

**Comment by mrleblanc101** [comment]
I'll try although I'm not sure I prefer this.
Can't it be an issue that the sprite is after the definition (use tag) ?

**Comment by oliverfindl** [comment]
Hello,

There was issue with [RegExp](https://en.wikipedia.org/wiki/Regular_expression) rule matching child node of [Vue SFC](https://vuejs.org/guide/single-file-components.html) root node (which is child node to template node). I did not consider there might be a condition (with ">" or ">=" operators) in root node as well.

Can you please explain in more detail why you don't like this solution?

Thanks

**Comment by mrleblanc101** [comment]
I found it weird that the definition would be after the use tag. I thought it might cause issue in old IE particularly.
But I think the DOM is parsed when it's fully loaded so it might not be an issue.

**Comment by oliverfindl** [comment]
Hello,

If you care about older IE users, you should [avoid](https://caniuse.com/#feat=svg) using SVGs at all. You can dig into [MDN](https://developer.mozilla.org/en-US/docs/Web/SVG) for more info.

I don't think this change will cause any observable issues. If so, please report it here and we can figure something out.

Thanks

**Comment by oliverfindl** [comment]
Closing this issue.

**Comment by mrleblanc101** [comment]
I found an issue.
Could we reopen ?
If my component has two root-nodes shown conditionnally (this is valid) as only one is shown at a time, my svg will always be in the v-else.
```
<template>
    <div v-if="someCondition">
        <img svg-inline src="...">
    </div>
    <div v-else>
        <!-- Sprite will be inserted here -->
    </div>
</template>

**Comment by oliverfindl** [comment]
Hello,

please continue in your newly opened [issue](https://github.com/oliverfindl/vue-svg-inline-loader/issues/16).

Thanks
