### ISSUE TITLE
Conditionnal root-node

### ISSUE THREAD

**Issue by mrleblanc101** [oliverfindl/vue-svg-inline-loader#16]
If my component has two root-nodes shown conditionally (this is valid as only one is shown at a time), my svg will always be in the v-else.
```
<template>
    <div v-if="someCondition">
        <img svg-inline src="...">
    </div>
    <div v-else>
        <!-- Sprite will be inserted here -->
    </div>
</template>
```

**Comment by oliverfindl** [comment]
Hello,

You are right! This won't work with current approach which is based on regular expression to [match](https://github.com/oliverfindl/vue-svg-inline-loader/blob/ad9167f844aac539c37a6171f0d4cb1ced692d3d/src/index.js#L83) last available position before template closing tag. I'm afraid, this approach can't handle situation with conditional root node (to be exactly correct, it cant handle conditional root node with `else` block or more `if`/`else if` blocks).

Solution would be to implement html parser (e.g.: [htmlparser2](https://github.com/fb55/htmlparser2)), which is my plan for next major version. Sadly, I don't have time for it right now.

As workaround you can wrap your conditional root node into `<div>...</div>`, which will become your new root node, and it should work as expected. If not, please let me know.
Eventually, if possible, you could split your component into 2 conditionals components. This should work too.

Thanks
