### ISSUE TITLE
Not working with Nuxt dynamic image

### ISSUE THREAD

**Issue by packytagliaferro** [oliverfindl/vue-svg-inline-loader#21]
Right now when I implement it with the src being dynamic it wont work:

in vue:

```
<li
                            class="w-1/5 hover:opacity-50"
                            v-for="(item, index) in  $store.state.socialMenu"
                            v-bind:key="index"
                        >
                            <a :href="item.link" class="mr-4 link" target="_blank">
                                <img
                                    svg-inline
                                    class="icon"
                                    :src="require('~/assets/svg/'+item.icon+'.svg')"
                                    :alt="item.name"
                                />
                            </a>
                        </li>
```

What is rendered for the image:

`<img svg-inline="" src="/_nuxt/assets/svg/facebook.svg" alt="Facebook" class="icon">
`
If I hard code in the src like `src="~/assets/svg/facebook.svg"` it will work fine but I need to load the images in a loop.

**Comment by oliverfindl** [comment]
Hello,

please check my answer [here](https://github.com/oliverfindl/vue-svg-inline-loader/issues/2#issuecomment-400548461).

If you have any questions, feel free to ask.

Thanks

**Comment by oliverfindl** [comment]
Closing this issue.
