### ISSUE TITLE
Plugin remove SVG with defs / linearGradient

### ISSUE THREAD

**Issue by ps-hidden** [oliverfindl/vue-svg-inline-loader#24]
Hi. I use your plugin and found next bug:
In component use `<img svg-inline svg-sprite src="home-arrow-down.svg" alt="">` and this svg file https://prnt.sc/oz801c.
In output we get svg without defs area (and without linearGradient)

**Comment by oliverfindl** [comment]
Hello,

please check my answer [here](https://github.com/oliverfindl/vue-svg-inline-loader/issues/11).

If you have any questions, feel free to ask.

Thanks

**Comment by ps-hidden** [comment]
Did not help.
config.module.rule("vue")
      .use("vue-svg-inline-loader")
      .loader("vue-svg-inline-loader")
      .options({
        svgo: false
      });

**Comment by oliverfindl** [comment]
Hello,

can you please attach your SVG file, so I can fiddle with it?

Thanks

**Comment by ps-hidden** [comment]
Yes, in zip. Git does not use svg :)
[home-arrow-down.zip](https://github.com/oliverfindl/vue-svg-inline-loader/files/3556418/home-arrow-down.zip)

**Comment by oliverfindl** [comment]
Hello,

just tested it, and it (kinda) works for me when [SVGO](https://github.com/svg/svgo) is disabled. Problem is with `svg-sprite` directive. Your SVG gets correctly inserted into sprites SVG (at end of your component), but when its referenced in code, whole `<defs>` part is missing. Issue here lies probably in using `<use>` more than once (which is what exactly `svg-sprite` directive does - it wraps your svg into `<use>` and then reference it in code).

If you remove `svg-sprite` directive, it will work correctly.

If you have any questions, feel free to ask.

Thanks

**Comment by ps-hidden** [comment]
It was more convenient to hide in the sprite :) But thanks anyway

**Comment by oliverfindl** [comment]
Sure, no problem.

Closing this issue.
