### ISSUE TITLE
Passing SVG as a prop

### ISSUE THREAD

**Issue by Scaalees** [oliverfindl/vue-svg-inline-loader#26]
I'm passing an imported SVG as a prop to my component. However my component is just rendering the `<img />` tag rather than converting to a SVG.

## Parent component 
```
<template>
  <div>
    <child-component :svg="SVG" />
  </div>
</template>
<script>
  import SVG from '@/assets/svgs/my-svg.svg';
  export default {
    data: () => ({
       SVG
    })
  }
</script>
```

## Child component
```
<template>
  <div>
    <img svg-inline :src="parentSVG" /> 
  </div>
</template>
<script>
  export default {
      props: {
        type: String,
        required: true,
      }
  }
</script>
```

## Renders as
```
<img svg-inline="" src="/_nuxt/assets/svgs/my-svg.svg">
```

I'm using the standard nuxt config.

**Comment by mrleblanc101** [comment]
Did you read the doc ?
This only work for img in the template.
Not img imported via JS

**Comment by oliverfindl** [comment]
Hello,

please check my answer [here](https://github.com/oliverfindl/vue-svg-inline-loader/issues/2#issuecomment-400548461).

If you have any questions, feel free to ask.

Thanks

**Comment by Scaalees** [comment]
No worries at all. Sorry for the confusion, didn't quite see the notice about it being only static

**Comment by adrianthedev** [comment]
[This](https://vue-svg-loader.js.org/) extension helped me out in the end.
