### ISSUE TITLE
Adding custom attr to replaced svg

### ISSUE THREAD

**Issue by mrleblanc101** [oliverfindl/vue-svg-inline-loader#27]
Hi,
It would be nice if we could add our own custom attrs to the SVG that is replaced via the config.
For example, we have an issue in IE11 where we need to add tabindex ="-1" and focusable="false"

**Comment by oliverfindl** [comment]
Hello,

I updated loader and published it to [npm](https://www.npmjs.com/package/vue-svg-inline-loader). Current version is [1.3.0](https://github.com/oliverfindl/vue-svg-inline-loader/releases/tag/v1.3.0).

Check [readme](https://github.com/oliverfindl/vue-svg-inline-loader) for default [configuration](https://github.com/oliverfindl/vue-svg-inline-loader#configuration).

Please give me feedback if it works as expected.

Thanks

**Comment by mrleblanc101** [comment]
Wow, that was fast. Thanks
