### ISSUE TITLE
Duplicate attribute: class

### ISSUE THREAD

**Issue by topclaudy** [oliverfindl/vue-svg-inline-loader#28]
When the SVG contains a 'class' attribute, the 'class' attribute got duplicated when we specify additional classes in the tag:

For example: 

`<img svg-inline class="svg-icon icon" src="eye.svg" alt="Watch" />`

Generates:

`<svg class="eye icon-eye" svg-inline="" class="svg-icon icon" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"  role="presentation" focusable="false" tabindex="-1"><circle cx="12" cy="12" r="3"/>...`

The classes 'eye' and 'icon-eye' are embedded in the SVG.

The compilation fails in this case

**Comment by oliverfindl** [comment]
Hello,

I updated loader and published it to [npm](https://www.npmjs.com/package/vue-svg-inline-loader). Current version is [1.3.1](https://github.com/oliverfindl/vue-svg-inline-loader/releases/tag/v1.3.1).

It's only hotfix. Proper fix would require some code refactoring, but I don't have time for it right now.

Please give me feedback if it works as expected.

Thanks

**Comment by topclaudy** [comment]
Fixed! Thanks :)
