### ISSUE TITLE
build fail on node.js version 6

### ISSUE THREAD

**Issue by peterhpchen** [oliverfindl/vue-svg-inline-loader#3]
Thank you making this amazing loader. But I met some issue on this loader.

Because `async` syntax does not be handled by node.js 6, the build failed.

https://github.com/oliverfindl/vue-svg-inline-loader/blob/cba590797e6b3bbdc388d74730eb958ee1270e91/src/index.js#L132

I think it should be transpiler to es5 for older node version.

Any idea?

Thanks again.

**Comment by oliverfindl** [comment]
Hello,

I added transpiled version. Please update loader to version [1.1.3](https://github.com/oliverfindl/vue-svg-inline-loader/releases/tag/v1.1.3) and please give feedback if it works or not. I don't have any node 6 environment.

Thanks

**Comment by peterhpchen** [comment]
That working fine on node 6 after update to 1.1.3.

Thank you very much.

**Comment by oliverfindl** [comment]
I'm glad it works.

Closing this issue.
