### ISSUE TITLE
Add accessibility tags and attributes

### ISSUE THREAD

**Issue by IlCallo** [oliverfindl/vue-svg-inline-loader#31]
As shown [here](https://css-tricks.com/accessible-svgs/).

- `alt` attribute should be translated into a `<title>` tag into the SVG ([support is very good](https://caniuse.com/#feat=mdn-svg_elements_title))
- `role="img"` should be added

**Comment by oliverfindl** [comment]
Hello,

although, this seems to be very good idea, it would very hard to implement it with current approach, which is using regular expression for parsing `*.svg` and `*.vue` files. Not to mention, it would conflict with [SVGO](https://github.com/svg/svgo) optimization or with original `title` tag when [SVGO](https://github.com/svg/svgo) optimization is disabled. I think, best solution would be, to let it be as it currently is. If someone wants this behavior, they can set `title` tag directly in svg file (and configure [SVGO](https://github.com/svg/svgo) option to preserve it) and omit `alt` attribute in `img` tag.

As for `role="img"`, you can set this attribute in [options](https://github.com/oliverfindl/vue-svg-inline-loader#configuration) - key `addAttributes`. Default role is set to `presentation`, which makes more sense to me.

If you have any more questions, feel free to ask.

Thanks

**Comment by IlCallo** [comment]
All clear, thanks!
I think managing the `alt` attribute would be better than requiring to manually add svg title, you could even reference SVG you cannot (or would not) modify. It would also keep the "img-like" look&feel consistent.

Also, I think it would be good to overwrite `title` tag when an `alt` is provided: you can just omit it if you want to use the original `title` tag.

This said, it can still be done with regexp, even if things get more complicated: first try to retrieve `alt` value and save it, then operate the replace you're using now.
At this point, if `alt` value was actually present, search and remove current `title` tag, if any, and operate a replace on the opening SVG tag adding the new `title` tag right after it.

It's a search and 2 replaces more than current implementation (I guess, I didn't checked the code yet), but being at compile time the performance impact won't be that harmful.

If `alt` attribute is found, it should also automatically disable `title` tag optimization flag.

Does this make sense for you?
If not, I'll just follow your suggestions or fork the project.
If yes, it doesn't seem a difficult task and I can probably try a PR.

**Comment by oliverfindl** [comment]
Hello,

It is no problem to implement it for me, but I'm worried about unnecessary code complexity at this point. I have slightly different solution in mind, which would require some minor code refactoring. I can look at it weekend.

I will update this issue, when new version is released.

Thanks

**Comment by IlCallo** [comment]
Thank you :)

**Comment by oliverfindl** [comment]
Hello,

I updated loader and published it to [npm](https://www.npmjs.com/package/vue-svg-inline-loader). Current version is [1.4.0](https://github.com/oliverfindl/vue-svg-inline-loader/releases/tag/v1.4.0).

There is new option `addTitle`. Check [readme](https://github.com/oliverfindl/vue-svg-inline-loader) for default [configuration](https://github.com/oliverfindl/vue-svg-inline-loader#configuration).

Please give me feedback if it works as expected.

Thanks

**Comment by IlCallo** [comment]
Works perfectly, thank you!
