### ISSUE TITLE
removing tabindex, role etc.

### ISSUE THREAD

**Issue by spacedawwwg** [oliverfindl/vue-svg-inline-loader#35]
I feel like I'm going insane but I can't figure out how to remove `tabindex` etc.

also, `src` is not being removed either

this is my config for gridsome:

```
chainWebpack(config) {
    config.module
      .rule('vue')
      .use('vue-svg-inline-loader')
      .loader('vue-svg-inline-loader')
      .options({
        removeAttributes: ['width', 'height', 'alt', 'src'],
        addAttributes: {
          focusable: false,
        },
      });
}
```

**Comment by oliverfindl** [comment]
Hello,

Can confirm this bug. It's due wrong order of attributes operations.

I updated loader and published it to [npm](https://www.npmjs.com/package/vue-svg-inline-loader). Current version is [1.4.4](https://github.com/oliverfindl/vue-svg-inline-loader/releases/tag/v1.4.4).

Please update loader and `removeAttributes: ["alt", "src", "tabindex"]` should solve your issue.

Please give me feedback if it works as expected.

Thanks

**Comment by oliverfindl** [comment]
Closing this issue.
