### ISSUE TITLE
Neighboring SVGs replace each other's styles

### ISSUE THREAD

**Issue by kovaletsyurii** [oliverfindl/vue-svg-inline-loader#45]
Hi there!
I has a few svgs with the same id attributes and different styles. So when I insert them inline - styles from one svg applies to other with the same id's (and its looks logically right), but do we have the way to incapsulate styles and id's inside the svg tag before converting them to inline? Can we add some "scoped: true" option to svg-inline directive or something like this?)

**Comment by oliverfindl** [comment]
Hello,

unfortunately, that won't be possible. Per definition, all ids have to be unique per document. You can not namespace them. You can namespace other selector, e.g.: classes, but not ids.

Namespacing is not supported by this loader (that's out of scope functionality). If you need it, you should do it manually or write your own SVG pre-processing [webpack](https://github.com/webpack/webpack) loader for this purpose.

If you have more questions, feel free to ask here.

Thanks.
