### ISSUE TITLE
Create a Nuxt Module export

### ISSUE THREAD

**Issue by mrleblanc101** [oliverfindl/vue-svg-inline-loader#53]
Hi,
I love this plugin, I currently use it in every Nuxt project I start.
But I have to use the `extends` key inside `nuxt.config.js` and copy/paster my config everytime.
I was wondering if it would be possible to add a Nuxt Module export (Something like: `vue-svg-inline-loader/nuxt`) so it could work seamlessly with Nuxt.

**Comment by oliverfindl** [comment]
Hello,

sorry, but I'm not familiar with [Nuxt](https://github.com/nuxt/nuxt.js) or its plugin architecture. This is [Webpack](https://github.com/webpack/webpack) plugin and extending key inside `nuxt.config.js` file is way, that [Nuxt](https://github.com/nuxt/nuxt.js) has chosen to handle such situations.

This loader is open source, so feel free to fork it, create [Nuxt](https://github.com/nuxt/nuxt.js) plugin and submit it as PR or publish it as your own package. I don't have capacity to follow and support such use cases for each [Webpack](https://github.com/webpack/webpack) based framework out there.

If you have more questions, feel free to ask here.

Thanks.

**Comment by mrleblanc101** [comment]
Nuxt is pretty much the only framework built on top of Vue. But sure, since there is an active maintainer I will look into opening a PR to add support for Nuxt. It should be pretty simple.

**Comment by oliverfindl** [comment]
Hello,

well, there are few:
- [Nuxt](https://nuxtjs.org/),
- [Gridsome](https://gridsome.org/),
- [Quasar](https://quasar.dev/),
- [Ionic](https://ionicframework.com/vue).

Feel free to add this functionality and submit PR for [Nuxt](https://github.com/nuxt/nuxt.js) use case.

Thanks.

**Comment by mrleblanc101** [comment]
None of them have a module system to extend the framework like Nuxt. They all use callback function in their config file like I did with Nuxt, but I'd rather have a plug-and-play option. I'll try to open à PR shortly.

**Comment by oliverfindl** [comment]
Hello,

I merged your PR and published it to [npm](https://www.npmjs.com/package/vue-svg-inline-loader). You can update package and test it.

Thanks.
