### ISSUE TITLE
Nuxt config not working

### ISSUE THREAD

**Issue by dominicpedro** [oliverfindl/vue-svg-inline-loader#55]
Get the error below:

```
   │   Error: Cannot find module 'vue-svg-inline-loader/nuxt'                                           │
```

I think its because in your packages.json you have not included the `nuxt` folder in the `files` so it doesn't come down when you install via npm.

**Comment by oliverfindl** [comment]
Hello,

sorry, this was an oversight at my end. Just published updated version to [npm](https://www.npmjs.com/package/vue-svg-inline-loader). You can update package and test it.

Thanks.

**Comment by oliverfindl** [comment]
Closing this issue.
