### ISSUE TITLE
Other options to use this plugin

### ISSUE THREAD

**Issue by bradleyw92** [oliverfindl/vue-svg-inline-loader#56]
Can you use this when loading an image in via a data return like below?

```
data() {
        return {
            lightSwitchTickIcon: require('../../images/svgs/toggle-switch-tick.svg'),
        }
},
```

`<span v-html="lightSwitchTickIcon"></span>`

**Comment by oliverfindl** [comment]
Hello,

unfortunately no, this is not how this plugin works. It parses your SFC file for `template` tag (and I think maybe `script` tag too - or it parsed it at one time, not sure if it still works this way) and searches for `img` tags tagged with chosen directive(s) which have `src` attribute set to valid SVG file. This happens on compile time, so no [Vue](https://github.com/vuejs/vue-next) related logic has has been triggered at this point.

In short, it needs to be structured like this:
```html
<img svg-inline src="./path/to/valid/file.svg" />
```
Where value in `src` have to be literal path to SVG file (no [Vue](https://github.com/vuejs/vue-next) variables).

And maybe I misunderstood your question. If you are asking, if this plugin can be used when you already have some logic (as mentioned in your post) in place, then yes, it can be used together and won't affect your logic or code.

If you have more questions, feel free to ask here.

Thanks.

**Comment by bradleyw92** [comment]
Completely understand. I tweaked the login in my component per your documentation and the inline SVG appeared. In this case I just wanted to check before I update all the other components.

**Comment by oliverfindl** [comment]
Closing this issue.
